config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    root 'store#index', as: 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>Pragprog Booksオンラインストア</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= form_tag store_path, class: 'locale', method: :get do %>
    <%= select_tag 'set_locale',
    options_for_select(LANGUAGES, I18n.locale.to_s),
    onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <div id="cart">
        <%= render @cart %>
      </div>

      <ul>
        <li><a href="http://www..."><%= t('.home') %></a></li>
        <li><a href="http://www.../faq"><%= t('.questions') %></a></li>
        <li><a href="http://www.../news"><%= t('.news') %></a></li>
        <li><a href="http://www.../contact"><%= t('.contact') %></a></li>
        <li><a><%= @time %></a></li>
        <% if @cart %>
        <li><%= link_to('カート', cart_path(@cart)) %></li>
        <% end %>
      </ul>

      <% if @user %>
      <ul>
        <li><a><%= "こんにちは！#{@user.name}さん" %></a></li>
        <li><%= link_to('注文',     orders_path)   %></li>
        <li><%= link_to('商品',     products_path) %></li>
        <li><%= link_to('ユーザー', users_path)    %></li>
      </ul>
      <%= button_to('ログアウト', logout_path, method: :delete) %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>